-- creating the table if it doesnt exist
CREATE TABLE IF NOT EXISTS NOMNOM (
NAME TEXT,
NEIGHBOURHOOD TEXT,
CUISINE TEXT,
REVIEW TEXT,
PRICE TEXT,
HEALTH TEXT
);

-- INSERTING SAMPLR DATA
INSERT INTO NOMNOM (NAME, NEIGHBOURHOOD, CUISINE, REVIEW, PRICE, HEALTH) VALUES
('Peter', 'Brooklyn', 'Steak', 4.4, '$$$$', 'A'),
('Jongro', 'Midtown', 'Korean', 3.5, '$$', 'A'),
('Pocha', 'Midtown', 'Pizza', 4, '$$$', 'B'),
('Lighthouse', 'Queens', 'Chinese', 3.9, '$', 'A'),
('Minca', 'Downtown', 'American', 4.6, '$$$', ''),
('Marea', 'Chinatown', 'Chinese', 3.0, '$$', ''),
('Dirty Candy', 'Uptown', 'Italian', 4.9, '$$$$', 'B'),
('Di Fara Pizza', 'Brooklyn', 'Pizza', 3.8, '$$$', 'A'),
('Golden Unicorn', 'Uptown', 'Italian', 3.8, '$$', 'A');

-- SELECT ALL RECORDS
SELECT * FROM NOMNOM;

-- SELECT DISTICT NEIGHBOURHOODS FROM THE NOMNOM TABLE
SELECT DISTINCT NEIGHBOURHOOD FROM NOMNOM;

-- SELECTING DISTINCT CUISINES
SELECT DISTINCT CUISINE FROM NOMNOM;

-- SELECT ALL RECORD WITH CHINESE CUISINE
SELECT * FROM NOMNOM WHERE CUISINE = 'Chinese';

-- SELECTING RECORDS WITH A REVIEW RATING OF 4 OR GREATER
SELECT * FROM NOMNOM WHERE REVIEW >= 4;

-- SELECTING RECORDS WITH ITALIAN CUISINE AND $$$ PRICE
SELECT * FROM NOMNOM WHERE CUISINE = 'Italian' AND PRICE = '$$$';

-- SELECT ALL REECORDS WITH CANDY CONTAINED IN THE NAME
SELECT * FROM NOMNOM WHERE NAME LIKE '%Candy%';

-- SELECTING RECORDS WHERE NEIGHBORHOOD IS MIDTOWN, DOWNTOWN OR CHINATOWN
SELECT * FROM NOMNOM
WHERE NEIGHBOURHOOD IN ('Midtown', 'Downtown', 'Chinatown');

-- SELECT THE TOP 4 RECORDS ORDERED BY REVIEW RATING IN DESCENTING ORDER
SELECT * FROM NOMNOM ORDER BY REVIEW DESC LIMIT 4;

SELECT * FROM NOMNOM;
SELECT * FROM NOMNOM LIMIT 5 OFFSET 2;