-- CREATE STUDENT TABLE IF IT DOES OT EXIST
-- NOT NULL IS USED FOR NAME TO ENSURE EVERY STUDENT HAS A RECORDED NAME
CREATE TABLE IF NOT EXISTS STUDENT (
    ROLL_NO PRIMARY KEY,
    NAME TEXT NOT NULL,
    ADDRESS TEXT,
    PHONE TEXT,
    AGE INTEGER
);

-- INSERT SAMPLE DATA INTO THE STUDENT TABLE
INSERT INTO STUDENT (ROLL_NO, NAME, ADDRESS, PHONE, AGE) VALUES
    ('1', 'RAM', 'DELHI', '*****', 18),
('2', 'RAMESH', 'GURGAON', '*****', 18),
('3', 'SUJIT', 'ROHTAK', '*****', 20),
('4', 'SURESH', 'DELHI', '*****', 18),
('5', 'AMAN', 'ROHTAK', '*****', 20),
('6', 'HARSH', 'GURGAON', '*****', 18);

-- SELECT ALL RECORDS FROM STUDENT TABLE TO VERIFY INSERTION
SELECT * FROM STUDENT;

-- QUERY STUDENTS WHO ARE 18 YEARS OLD AND LIVE IN DELHI
SELECT * FROM STUDENT WHERE AGE = 18 AND ADDRESS = 'DELHI';

-- QUERY STUDENTS WHO ARE 18 YEARS OLD AND NAMED RAM
SELECT * FROM STUDENT WHERE AGE = 18 AND NAME = 'RAM';

-- QUERY STUDENTS NAMED RAM OR SUJIT
SELECT * FROM STUDENT WHERE NAME = 'RAM' OR NAME = 'SUJIT';

-- QUERY STUDENTS AGED 18 AND NAMED RAM OR RAMESH
SELECT * FROM STUDENT WHERE AGE = 18 AND (NAME = 'RAM' OR NAME = 'RAMESH');